"""Static, non-editable timezone catalog.

Transcribed from the user-provided reference script
(vision_ai_schema_postgres.sql) — its `time_zone_configurations` table and
INSERT data only. Every other table in that file (organization_details,
priority_configuration, roles, user_details, zone_details, kpi_models,
kpi_configuration, camera_details, jobs, alerts, alert_frames, email_logs,
audit_logs) is a different, earlier/abandoned schema attempt superseded by
this project's own app/db/models — not used here.

Each row: (abbreviation, timezone_name, utc_offset, gmt_offset). Loaded into
the existing Timezone model (app/db/models/domain_config.py, table
"timezones") — note `abbreviation` is NOT unique in this data (e.g. "AST"
covers both Atlantic Standard Time and Arabia Standard Time), so callers
must always reference a timezone by its integer id, never by abbreviation.
"""

TIMEZONE_SEED_ROWS: list[tuple[str, str, str, str]] = [
    ("ACDT", "Australian Central Daylight Savings Time", "UTC+10:30", "GMT+10:30"),
    ("ACST", "Australian Central Standard Time", "UTC+9:30", "GMT+9:30"),
    ("ACT", "Acre Time", "UTC-5", "GMT-5"),
    ("ACWST", "Australian Central Western Standard Time", "UTC+8:45", "GMT+8:45"),
    ("ADT", "Atlantic Daylight Time", "UTC-3", "GMT-3"),
    ("AEDT", "Australian Eastern Daylight Savings Time", "UTC+11", "GMT+11"),
    ("AEST", "Australian Eastern Standard Time", "UTC+10", "GMT+10"),
    ("AFT", "Afghanistan Time", "UTC+4:30", "GMT+4:30"),
    ("AKDT", "Alaska Daylight Time", "UTC-8", "GMT-8"),
    ("AKST", "Alaska Standard Time", "UTC-9", "GMT-9"),
    ("AMST", "Amazon Summer Time", "UTC-3", "GMT-3"),
    ("AMT", "Amazon Time", "UTC-4", "GMT-4"),
    ("AMT", "Armenia Time", "UTC+4", "GMT+4"),
    ("ART", "Argentina Time", "UTC-3", "GMT-3"),
    ("AST", "Atlantic Standard Time", "UTC-4", "GMT-4"),
    ("AST", "Arabia Standard Time", "UTC+3", "GMT+3"),
    ("AT", "Atlantic Time", "UTC-4/UTC-3", "GMT-4/GMT-3"),
    ("AWST", "Australian Western Standard Time", "UTC+8", "GMT+8"),
    ("AZOST", "Azores Summer Time", "UTC+0", "GMT+0"),
    ("AZOT", "Azores Standard Time", "UTC-1", "GMT-1"),
    ("AZT", "Azerbaijan Time", "UTC+4", "GMT+4"),
    ("BDT", "Brunei Time", "UTC+8", "GMT+8"),
    ("BIT", "Baker Island Time", "UTC-12", "GMT-12"),
    ("BNT", "Brunei Darussalam Time", "UTC+8", "GMT+8"),
    ("BOT", "Bolivia Time", "UTC-4", "GMT-4"),
    ("BRST", "Brasilia Summer Time", "UTC-2", "GMT-2"),
    ("BRT", "Brasilia Time", "UTC-3", "GMT-3"),
    ("BST", "British Summer Time", "UTC+1", "GMT+1"),
    ("BST", "Bangladesh Standard Time", "UTC+6", "GMT+6"),
    ("BST", "Bougainville Standard Time", "UTC+11", "GMT+11"),
    ("BTT", "Bhutan Time", "UTC+6", "GMT+6"),
    ("CAT", "Central Africa Time", "UTC+2", "GMT+2"),
    ("CCT", "Cocos Islands Time", "UTC+6:30", "GMT+6:30"),
    ("CDT", "Central Daylight Time", "UTC-5", "GMT-5"),
    ("CDT", "Cuba Daylight Time", "UTC-4", "GMT-4"),
    ("CEST", "Central European Summer Time", "UTC+2", "GMT+2"),
    ("CET", "Central European Time", "UTC+1", "GMT+1"),
    ("CHADT", "Chatham Daylight Time", "UTC+13:45", "GMT+13:45"),
    ("CHAST", "Chatham Standard Time", "UTC+12:45", "GMT+12:45"),
    ("CHOST", "Choibalsan Summer Time", "UTC+9", "GMT+9"),
    ("CHOT", "Choibalsan Standard Time", "UTC+8", "GMT+8"),
    ("CHST", "Chamorro Standard Time", "UTC+10", "GMT+10"),
    ("CHUT", "Chuuk Time", "UTC+10", "GMT+10"),
    ("CIST", "Clipperton Island Standard Time", "UTC-8", "GMT-8"),
    ("CIT", "Central Indonesia Time", "UTC+8", "GMT+8"),
    ("CKT", "Cook Island Time", "UTC-10", "GMT-10"),
    ("CLST", "Chile Summer Time", "UTC-3", "GMT-3"),
    ("CLT", "Chile Standard Time", "UTC-4", "GMT-4"),
    ("COST", "Colombia Summer Time", "UTC-4", "GMT-4"),
    ("COT", "Colombia Time", "UTC-5", "GMT-5"),
    ("CST", "Central Standard Time", "UTC-6", "GMT-6"),
    ("CST", "China Standard Time", "UTC+8", "GMT+8"),
    ("CST", "Cuba Standard Time", "UTC-5", "GMT-5"),
    ("CT", "Central Time", "UTC-6/UTC-5", "GMT-6/GMT-5"),
    ("CVT", "Cape Verde Time", "UTC-1", "GMT-1"),
    ("CWST", "Central Western Standard Time", "UTC+8:45", "GMT+8:45"),
    ("CXT", "Christmas Island Time", "UTC+7", "GMT+7"),
    ("DAVT", "Davis Time", "UTC+7", "GMT+7"),
    ("DDUT", "Dumont d'Urville Time", "UTC+10", "GMT+10"),
    ("EASST", "Easter Island Summer Time", "UTC-5", "GMT-5"),
    ("EAST", "Easter Island Standard Time", "UTC-6", "GMT-6"),
    ("EAT", "East Africa Time", "UTC+3", "GMT+3"),
    ("ECT", "Ecuador Time", "UTC-5", "GMT-5"),
    ("EDT", "Eastern Daylight Time", "UTC-4", "GMT-4"),
    ("EEST", "Eastern European Summer Time", "UTC+3", "GMT+3"),
    ("EET", "Eastern European Time", "UTC+2", "GMT+2"),
    ("EGST", "Eastern Greenland Summer Time", "UTC+0", "GMT+0"),
    ("EGT", "Eastern Greenland Time", "UTC-1", "GMT-1"),
    ("EIT", "Eastern Indonesian Time", "UTC+9", "GMT+9"),
    ("EST", "Eastern Standard Time", "UTC-5", "GMT-5"),
    ("ET", "Eastern Time", "UTC-5/UTC-4", "GMT-5/GMT-4"),
    ("FET", "Further-eastern European Time", "UTC+3", "GMT+3"),
    ("FJT", "Fiji Time", "UTC+12", "GMT+12"),
    ("FKST", "Falkland Islands Summer Time", "UTC-3", "GMT-3"),
    ("FKT", "Falkland Islands Time", "UTC-4", "GMT-4"),
    ("FNT", "Fernando de Noronha Time", "UTC-2", "GMT-2"),
    ("GALT", "Galapagos Time", "UTC-6", "GMT-6"),
    ("GAMT", "Gambier Islands", "UTC-9", "GMT-9"),
    ("GET", "Georgia Standard Time", "UTC+4", "GMT+4"),
    ("GFT", "French Guiana Time", "UTC-3", "GMT-3"),
    ("GILT", "Gilbert Island Time", "UTC+12", "GMT+12"),
    ("GIT", "Gambier Island Time", "UTC-9", "GMT-9"),
    ("GMT", "Greenwich Mean Time", "UTC+0", "GMT+0"),
    ("GST", "Gulf Standard Time", "UTC+4", "GMT+4"),
    ("GST", "South Georgia Time", "UTC-2", "GMT-2"),
    ("GYT", "Guyana Time", "UTC-4", "GMT-4"),
    ("HADT", "Hawaii-Aleutian Daylight Time", "UTC-9", "GMT-9"),
    ("HAST", "Hawaii-Aleutian Standard Time", "UTC-10", "GMT-10"),
    ("HKT", "Hong Kong Time", "UTC+8", "GMT+8"),
    ("HMT", "Heard and McDonald Islands Time", "UTC+5", "GMT+5"),
    ("HOVST", "Khovd Summer Time", "UTC+8", "GMT+8"),
    ("HOVT", "Khovd Standard Time", "UTC+7", "GMT+7"),
    ("ICT", "Indochina Time", "UTC+7", "GMT+7"),
    ("IDT", "Israel Daylight Time", "UTC+3", "GMT+3"),
    ("IOT", "Indian Chagos Time", "UTC+6", "GMT+6"),
    ("IRDT", "Iran Daylight Time", "UTC+4:30", "GMT+4:30"),
    ("IRKT", "Irkutsk Time", "UTC+8", "GMT+8"),
    ("IRST", "Iran Standard Time", "UTC+3:30", "GMT+3:30"),
    ("IST", "Indian Standard Time", "UTC+5:30", "GMT+5:30"),
    ("IST", "Irish Standard Time", "UTC+1", "GMT+1"),
    ("IST", "Israel Standard Time", "UTC+2", "GMT+2"),
    ("JST", "Japan Standard Time", "UTC+9", "GMT+9"),
    ("KGT", "Kyrgyzstan time", "UTC+6", "GMT+6"),
    ("KOST", "Kosrae Time", "UTC+11", "GMT+11"),
    ("KRAT", "Krasnoyarsk Time", "UTC+7", "GMT+7"),
    ("KST", "Korea Standard Time", "UTC+9", "GMT+9"),
    ("LHDT", "Lord Howe Daylight Time", "UTC+11", "GMT+11"),
    ("LHST", "Lord Howe Standard Time", "UTC+10:30", "GMT+10:30"),
    ("LINT", "Line Islands Time", "UTC+14", "GMT+14"),
    ("MAGT", "Magadan Time", "UTC+11", "GMT+11"),
    ("MART", "Marquesas Islands Time", "UTC-9:30", "GMT-9:30"),
    ("MAWT", "Mawson Station Time", "UTC+5", "GMT+5"),
    ("MDT", "Mountain Daylight Time", "UTC-6", "GMT-6"),
    ("MHT", "Marshall Islands", "UTC+12", "GMT+12"),
    ("MIST", "Macquarie Island Station Time", "UTC+11", "GMT+11"),
    ("MIT", "Marquesas Islands Time", "UTC-9:30", "GMT-9:30"),
    ("MMT", "Myanmar Standard Time", "UTC+6:30", "GMT+6:30"),
    ("MSK", "Moscow Time", "UTC+3", "GMT+3"),
    ("MST", "Mountain Standard Time", "UTC-7", "GMT-7"),
    ("MST", "Malaysia Standard Time", "UTC+8", "GMT+8"),
    ("MT", "Mountain Time", "UTC-7/UTC-6", "GMT-7/GMT-6"),
    ("MUT", "Mauritius Time", "UTC+4", "GMT+4"),
    ("MVT", "Maldives Time", "UTC+5", "GMT+5"),
    ("MYT", "Malaysia Time", "UTC+8", "GMT+8"),
    ("NCT", "New Caledonia Time", "UTC+11", "GMT+11"),
    ("NDT", "Newfoundland Daylight Time", "UTC-2:30", "GMT-2:30"),
    ("NFT", "Norfolk Time", "UTC+11", "GMT+11"),
    ("NPT", "Nepal Time", "UTC+5:45", "GMT+5:45"),
    ("NRT", "Nauru Time", "UTC+12", "GMT+12"),
    ("NST", "Newfoundland Standard Time", "UTC-3:30", "GMT-3:30"),
    ("NT", "Newfoundland Time", "UTC-3:30", "GMT-3:30"),
    ("NUT", "Niue Time", "UTC-11", "GMT-11"),
    ("NZDT", "New Zealand Daylight Time", "UTC+13", "GMT+13"),
    ("NZST", "New Zealand Standard Time", "UTC+12", "GMT+12"),
    ("OMST", "Omsk Time", "UTC+6", "GMT+6"),
    ("ORAT", "Oral Time", "UTC+5", "GMT+5"),
    ("PDT", "Pacific Daylight Time", "UTC-7", "GMT-7"),
    ("PET", "Peru Time", "UTC-5", "GMT-5"),
    ("PETT", "Kamchatka Time", "UTC+12", "GMT+12"),
    ("PGT", "Papua New Guinea Time", "UTC+10", "GMT+10"),
    ("PHOT", "Phoenix Island Time", "UTC+13", "GMT+13"),
    ("PhST", "Philippine Standard Time", "UTC+8", "GMT+8"),
    ("PHT", "Philippine Time", "UTC+8", "GMT+8"),
    ("PKT", "Pakistan Standard Time", "UTC+5", "GMT+5"),
    ("PMDT", "Saint Pierre and Miquelon Daylight time", "UTC-2", "GMT-2"),
    ("PMST", "Saint Pierre and Miquelon Standard Time", "UTC-3", "GMT-3"),
    ("PONT", "Pohnpei Standard Time", "UTC+11", "GMT+11"),
    ("PST", "Pacific Standard Time", "UTC-8", "GMT-8"),
    ("PT", "Pacific Time", "UTC-8/UTC-7", "GMT-8/GMT-7"),
    ("PWT", "Palau Time", "UTC+9", "GMT+9"),
    ("PYST", "Paraguay Summer Time", "UTC-3", "GMT-3"),
    ("PYT", "Paraguay Time", "UTC-4", "GMT-4"),
    ("RET", "Réunion Time", "UTC+4", "GMT+4"),
    ("ROTT", "Rothera Research Station Time", "UTC-3", "GMT-3"),
    ("SAKT", "Sakhalin Island time", "UTC+11", "GMT+11"),
    ("SAMT", "Samara Time", "UTC+4", "GMT+4"),
    ("SAST", "South African Standard Time", "UTC+2", "GMT+2"),
    ("SBT", "Solomon Islands Time", "UTC+11", "GMT+11"),
    ("SCT", "Seychelles Time", "UTC+4", "GMT+4"),
    ("SGT", "Singapore Time", "UTC+8", "GMT+8"),
    ("SLST", "Sri Lanka Standard Time", "UTC+5:30", "GMT+5:30"),
    ("SRET", "Srednekolymsk Time", "UTC+11", "GMT+11"),
    ("SRT", "Suriname Time", "UTC-3", "GMT-3"),
    ("SST", "Samoa Standard Time", "UTC-11", "GMT-11"),
    ("SYOT", "Showa Station Time", "UTC+3", "GMT+3"),
    ("TAHT", "Tahiti Time", "UTC-10", "GMT-10"),
    ("TFT", "French Southern and Antarctic Time", "UTC+5", "GMT+5"),
    ("THA", "Thailand Standard Time", "UTC+7", "GMT+7"),
    ("TJT", "Tajikistan Time", "UTC+5", "GMT+5"),
    ("TKT", "Tokelau Time", "UTC+13", "GMT+13"),
    ("TLT", "Timor Leste Time", "UTC+9", "GMT+9"),
    ("TMT", "Turkmenistan Time", "UTC+5", "GMT+5"),
    ("TOT", "Tonga Time", "UTC+13", "GMT+13"),
    ("TRT", "Turkey Time", "UTC+3", "GMT+3"),
    ("TVT", "Tuvalu Time", "UTC+12", "GMT+12"),
    ("ULAST", "Ulaanbaatar Summer Time", "UTC+9", "GMT+9"),
    ("ULAT", "Ulaanbaatar Standard Time", "UTC+8", "GMT+8"),
    ("USZ1", "Kaliningrad Time", "UTC+2", "GMT+2"),
    ("UTC", "Coordinated Universal Time", "UTC", "GMT"),
    ("UYST", "Uruguay Summer Time", "UTC-2", "GMT-2"),
    ("UYT", "Uruguay Standard Time", "UTC-3", "GMT-3"),
    ("UZT", "Uzbekistan Time", "UTC+5", "GMT+5"),
    ("VET", "Venezuelan Standard Time", "UTC-4", "GMT-4"),
    ("VLAT", "Vladivostok Time", "UTC+10", "GMT+10"),
    ("VOLT", "Volgograd Time", "UTC+4", "GMT+4"),
    ("VOST", "Vostok Station Time", "UTC+6", "GMT+6"),
    ("VUT", "Vanuatu Time", "UTC+11", "GMT+11"),
    ("WAKT", "Wake Island Time", "UTC+12", "GMT+12"),
    ("WAST", "West Africa Summer Time", "UTC+2", "GMT+2"),
    ("WAT", "West Africa Time", "UTC+1", "GMT+1"),
    ("WEST", "Western European Summer Time", "UTC+1", "GMT+1"),
    ("WET", "Western European Time", "UTC+0", "GMT+0"),
    ("WFT", "Wallis and Futuna Time", "UTC+12", "GMT+12"),
    ("WGST", "West Greenland Summer Time", "UTC-2", "GMT-2"),
    ("WGST", "West Greenland Time", "UTC-3", "GMT-3"),
    ("WIB", "Western Indonesia Time", "UTC+7", "GMT+7"),
    ("WIT", "Eastern Indonesia Time", "UTC+9", "GMT+9"),
    ("WST", "Western Standard Time", "UTC+8", "GMT+8"),
    ("YAKT", "Yakutsk Time", "UTC+9", "GMT+9"),
    ("YEKT", "Yekaterinburg Time", "UTC+5", "GMT+5"),
]
